### PR TITLE
Added support for immutablejs

### PR DESCRIPTION
**Pull request by actra-gschuster**

### CODE REVIEW

**Comment by rt2zz** [comment]
@actra-gschuster thanks for contributing, however we cannot reasonably expect all users to have or add immutablejs. It looks like the only way to reasonably achieve this is to make a separate transform with immutable support. Following the naming convention of the ecosystem you might call the modules something like `redux-persist-transform-filter-immutable`. Long but explicit :)

**Comment by actra-gschuster** [comment]
Using immutablejs is optional, it still supports plain objects.
But nevermind, I'll set up a repo and publish it there.

**Comment by rt2zz** [comment]
immutable objects is optional, but with this PR having the dependency is required

**Comment by edy** [comment]
closed. see above comments and https://github.com/actra-development/redux-persist-transform-filter-immutable

**Pull request closed without merging**
