### PR TITLE
Deep cloning of state inorder to avoid state properties to be deleted while blacklisting nested properties as Object.assign does shallow copy

### PR DESCRIPTION
**Pull request by himsajjan**
Can you please review the pull request as soon as possible and please let me know the feedback. Thank you.

### CODE REVIEW

**Comment by himsajjan** [comment]
Hi, can you please check this pull request. Thanks

**Comment by edy** [comment]
Hi @himsajjan, thank you for this PR and sorry for the delay. I'll merge this PR later this evening.

**Comment by edy** [comment]
@himsajjan would you please revert the changes you made in the package.json als package-lock.json.

**Comment by himsajjan** [comment]
Thanks edy, I have reverted package.json and package.lock.json file changes

**Comment by edy** [comment]
I have one more request. You import cloneDeep from `lodash/cloneDeep`. I'd like tom import it from `lodash.cloneDeep`, so nobody would have to install the whole lodash bloat

**Comment by himsajjan** [comment]
Changed, imported cloneDeep from lodash.cloneDeep

**Comment by edy** [comment]
published as 0.0.18

**Pull request merged**
